% generate_ascii_catalog: generates ASCII catalog of results of DLA
% search

catalog = load(sprintf('%s/catalog', processed_directory(release)));

load(sprintf('%s/dla_samples',       processed_directory(training_release)));
load(sprintf('%s/processed_qsos_%s', processed_directory(release), test_set_name));

fid = fopen(sprintf('%s/%s_dla_samples.dat',      ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

for i = 1:numel(offset_samples)
  fprintf(fid, '%06f %09f\n', ...
          offset_samples(i),  ...
          log_nhi_samples(i));
end

fclose(fid);

fid = fopen(sprintf('%s/%s_spectra.dat',          ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

for i = 1:numel(catalog.z_qsos)
  fprintf(fid, ...
          '%09i %-18s %04i %05i %04i %011.7f %+011.7f %06.4f %08.4f %i%i%i%i\n', ...
          catalog.thing_ids(i),               ...
          deblank(catalog.sdss_names{i}),     ...
          catalog.plates(i),                  ...
          catalog.mjds(i),                    ...
          catalog.fiber_ids(i),               ...
          catalog.ras(i),                     ...
          catalog.decs(i),                    ...
          catalog.z_qsos(i),                  ...
          catalog.snrs(i),                    ...
          bitget(catalog.filter_flags(i), 1), ...
          bitget(catalog.filter_flags(i), 2), ...
          bitget(catalog.filter_flags(i), 3), ...
          bitget(catalog.filter_flags(i), 4)  ...
          );
end

fclose(fid);

fid = fopen(sprintf('%s/%s_results.dat',          ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

searched_ind = find(test_ind);

for i = 1:numel(searched_ind)
  catalog_ind = searched_ind(i);
  fprintf(fid, ...
          '%09i %-18s %04i %05i %04i %011.7f %+011.7f %06.4f %08.4f ', ...
          catalog.thing_ids(catalog_ind),           ...
          deblank(catalog.sdss_names{catalog_ind}), ...
          catalog.plates(catalog_ind),              ...
          catalog.mjds(catalog_ind),                ...
          catalog.fiber_ids(catalog_ind),           ...
          catalog.ras(catalog_ind),                 ...
          catalog.decs(catalog_ind),                ...
          catalog.z_qsos(catalog_ind),              ...
          catalog.snrs(catalog_ind)                 ...
          );

  fprintf(fid, ...
          '%06.4f %06.4f %8.5f %8.5f %12.5e %12.5e %s %s ', ...
          min_z_dlas(i),             ...
          max_z_dlas(i),             ...
          log_priors_no_dla(i),      ...
          log_priors_dla(i),         ...
          log_likelihoods_no_dla(i), ...
          log_likelihoods_dla(i),    ...
          regexprep(sprintf('%0.5e', model_posteriors(i, 1)), ...
                    'e([+-])(\d\d)$', 'e$10$2'),              ...
          regexprep(sprintf('%0.5e', model_posteriors(i, 2)), ...
                    'e([+-])(\d\d)$', 'e$10$2')               ...
          );

  [~, map_ind] = nanmax(sample_log_likelihoods_dla(i, :));

  map_z_dla = min_z_dlas(i) + ...
      (max_z_dlas(i) - min_z_dlas(i)) * offset_samples(map_ind);

  % interweave z_DLA and log N_HI values
  fprintf(fid, '%06.4f %07.4f\n', ...
          map_z_dla, ...
          log_nhi_samples(map_ind));
end

fclose(fid);